### ISSUE TITLE
Some blocks of Powered UP are not working properly

### ISSUE THREAD

**Issue by Evolution-detector** [bricklife/scratch-lego-bluetooth-extensions#13]
Hello.
Thank you very much for creating the extension that allows us to use Scratch to control the other hubs we have on hand.

I have a Lego 88009 hub on hand. 
![88ea993e4542ea913b0c5102fa88930](https://user-images.githubusercontent.com/64944480/200994985-845248dc-b504-43e4-8c51-29c6165311de.jpg)

I am using the following blocks and I find that they do not perform properly. They do light up a bit when I click on them in Scratch, but the motor I have connected does not do anything.
The "Start" and "Stop" blocks at the top work fine.
![image](https://user-images.githubusercontent.com/64944480/200995089-2c346650-b677-4b5e-aaca-11705bf9b9ed.png)

I would like to know if the following blocks control the motors as well as the top two blocks, or if they need to be used with some specific external device?

**Comment by Evolution-detector** [comment]
My browser:
Microsoft Edge version 107.0.1418.35 (official version) (64-bit)

My computer:
Windows 10 Professional Edition 21H1

My Scratch Link:
1.4.3.0

**Comment by bricklife** [comment]
Your motor 45303 does not have any rotation sensor. So you cannot use these blocks because they are related to speed, rotation, or position.

**Comment by Evolution-detector** [comment]
Understood, thank you very much for your prompt reply.

**Comment by Evolution-detector** [comment]
I just purchased two motors that are said to have precise control ability, but I still couldn't make those five blocks work.
![image](https://user-images.githubusercontent.com/64944480/202994951-5873242b-abd4-45dc-a5b9-abaa8b3a1d39.png)
https://www.lego.com/en-gb/product/medium-linear-motor-88008

![image](https://user-images.githubusercontent.com/64944480/202995443-bcdacd85-8e9c-4b16-82e5-bf107cee827d.png)
https://www.lego.com/en-gb/product/technic-large-motor-88013

**Comment by bricklife** [comment]
Weird.. These blocks completely works with my hub and motors, 88009, 88008 and 88013. Is the version of firmware installed on your hub the latest?

**Comment by Evolution-detector** [comment]
![6a51a419ec77ca6fe670cc028eff761](https://user-images.githubusercontent.com/64944480/203211939-754618fd-47c6-4865-9dce-776b36ba5682.jpg)
How do I upgrade the firmware?
I downloaded the official Powered UP App, which can connect to the 88009 Hub and display the correct logo normally. On the connection screen, you see the name of the Hub and a number that I assume is the firmware version number. (It says 1.1.1.1)
For some reason, my phone can only run App version 3.8.0. the latest version of the App is 3.9.1. According to the description, the latest version only adds the Holiday Main Street (10308) theme.
https://www.lego.com/zh-cn/service/device-guide/powered-up
I can't find a place to update the firmware in this App.

**Comment by bricklife** [comment]
Hmm... Could you try using LEGO BLE extension instead and tell me what the firmware version is as follows? I'd like to know whether your Bluetooth communication works correctly or` not.

![image](https://user-images.githubusercontent.com/266357/203701832-b6bd919c-c0c1-457b-a94b-17b334a54173.png)

**Comment by Evolution-detector** [comment]
The firmware number is shown in the figure. In the LEGO BLE extension, I connected the 88013 but only the blocks that control the color of the light are available.
![image](https://user-images.githubusercontent.com/64944480/203807375-6bf9597c-9c7c-4456-b29f-9328beb3b850.png)

**Comment by bricklife** [comment]
Oh, I think `1.0.01.0000` is the first version of the firmware... Please try to update it to the new one using the following way:
https://pybricks.com/install/technic-boost-city/#restoring-the-original-firmware

**Comment by Evolution-detector** [comment]
I updated the firmware to version 1.1.02.0000.
It worked, thank you very much.
