### ISSUE TITLE
does spike prime legacy have sensors command

### ISSUE THREAD

**Issue by cklau75** [bricklife/scratch-lego-bluetooth-extensions#15]
Hi would like to know if spike prime legacy support sensort? Because I can't seem to find any commang there. Also I did try to connect using the spike prime essential, but it cannot connect the hub to the spike prime legacy. Any workaround for this?

**Comment by OsherRobotec** [comment]
Hi,
I have the same problem.
How we can duplicate the sensor commands from Spike Essential to Prime?
We are trying to help our students to use the Spike Prime from scratch but the only way is to create the same commands we have on the Essential to Prime.
We would appreciate your help,
Thank you.

**Comment by bricklife** [comment]
The extension for SPIKE Prime Legacy (v2.x) is an experimental project and it have been unstable. So I deprecate it today.

There is a plan to make a new extension for SPIKE Prime v3, but the development is a little bit hard. Please wait patiently.
