### ISSUE TITLE
Any chance to add updated extension for boost set

### ISSUE THREAD

**Issue by RothMick** [bricklife/scratch-lego-bluetooth-extensions#4]
Within official Lego boost extension, the blocks for distance are missing and won't be added by official team. Maybe an extended version would be a perfect addition here?
It looks like it could be done easily for people who knows, what needs to be done: https://github.com/LLK/scratch-vm/issues/2210

**Comment by bricklife** [comment]
@RothMick Thank you for your suggestion. I have not planned any BOOST extension, but creating any advanced version of it would be great.

Anyway, you can use my "LEGO BLE" extension with your BOOST and get distance value from it. Please try it.
