### ISSUE TITLE
Extension load into Xcratch doesn't work

### ISSUE THREAD

**Issue by bosnivan** [bricklife/scratch-lego-bluetooth-extensions#7]
When I try to load extension(s) into [Xcratch](https://xcratch.github.io/editor/) it results with:
> Could not get extension from: https://bricklife.com/scratch-gui/xcratch/spikeprime.mjs

**Comment by RBTELLOBOOST** [comment]
Same problem

thanks to help us

Romain

**Comment by markakis-sch** [comment]
I got the same massage on [https://xcratch.github.io/editor/](https://xcratch.github.io/editor) for spike essential extension:

Could not get extension from: [https://bricklife.com/scratch-gui/xcratch/spikeessential.mjs](https://bricklife.com/scratch-gui/xcratch/spikeessential.mjs)

**Comment by bricklife** [comment]
@bosnivan @RBTELLOBOOST @markakis-sch 
Thank you all for reporting this issue. I just fixed all the mjs files I published. Please try them again.
