### ISSUE TITLE
needs to get a xcratch with Tello drone and Lego extension

### ISSUE THREAD

**Issue by RBTELLOBOOST** [bricklife/scratch-lego-bluetooth-extensions#9]
Hello

I am trying to get a scratch3 plateforme whcich can use tello drone and lego extensions (lego boost and spyke prime).

By today, You provide extensions for lego and iit is fine for me
At the same time, I get a desktop scratch3 apps developped by https://github.com/kebhr/scratch3-tello which works for tello but some connecting problems with legoboost (and no spyke)

I can I can merge these elements to get a complete plateform with tello and lego boost and spyke?

I do need this for traing applications

Thanks

Romain (not experienced in software science...)

**Comment by bricklife** [comment]
@RBTELLOBOOST Tello requires Wi-Fi connection to control. So I think we cannot create any Xcratch extension for Tello.

The connection problems with BOOST can be fixed by updating the base code of Scratch. If you need it, please ask the developer of scratch3-tello.
